FUND_MAPPING = {
    "ABF Singapore Bond Index": "ASNGF",
    "AIA Acorns of Asia": "AIA",
    "AIA Elite Adventurous SGD": "AOA",
    "AIA Elite Balanced SGD": "AOM",
    "AIA Elite Conservative SGD": "AOK",
    "AIA Emerging Markets Balanced": "AOA",
    "AIA Emerging Markets Equity": "VWO",
    "AIA European Equity": "VGK",
    "AIA Global Adventurous Income": "AOA",
    "AIA Global Balanced": "AOR",
    "AIA Global Bond": "BND",
    "AIA Global Dynamic Income": "PDI",
    "AIA Global Equity": "VT",
    "AIA Global Property Returns": "VNQ",
    "AIA Global Technology": "XLK",
    "AIA Greater China Balanced": "AOR",
    "AIA Greater China Equity": "MCHI",
    "AIA Growth": "VUG",
    "AIA India Balanced": "AOR",
    "AIA India Equity": "INDA",
    "AIA India Opportunities": "SMIN",
    "AIA International Health Care": "IXJ",
    "AIA Japan Balanced": "AOR",
    "AIA Japan Equity": "EWJ",
    "AIA Multi Select 30": "AOK",
    "AIA Multi Select 50": "AOM",
    "AIA Multi Select 70": "AOA",
    "AIA Portfolio 30": "AOK",
    "AIA Portfolio 50": "AOM",
    "AIA Portfolio 70": "AOA",
    "AIA Portfolio 100": "VT",
    "AIA Regional Equity": "VPL",
    "AIA Regional Fixed Income": "EMB",
    "AIA S$ Money Market": "BIL",
    "AIA Shariah Global Diversified": "SPUS",
    "AIA Sustainable Multi-Thematic": "ICLN",
    "AIA US Equity": "IVV",

    # Indices / Assets
    "S&P 500 Index": "^GSPC",
    "AEX": "^AEX",
    "ATX": "^ATX",
    "BEL 20": "^BFX",
    "BIST 100": "XU100.IS",
    "Bovespa": "^BVSP",
    "BSE Sensex 30": "^BSESN",
    "Budapest SE": "^BUX",

    # Stocks / Crypto
    "Apple Inc": "AAPL",
    "ARK Innovation": "ARKK",
    "Bank of America": "BAC",
    "Berkshire Hathaway A": "BRK-A",
    "Bitcoin": "BTC-USD",
    "ASML Holding ADR": "ASML"
}

DEFAULT_BENCHMARK = "AIA US Equity"
START_DATE = "2016-01-04"
